package com.ccthanking.business.sgenter;

import com.ccthanking.business.sgenter.vo.SgBbPojo;
import com.ccthanking.business.sgenter.vo.SgBbPddjPojo;

global SgBbPojo retPojo;

//项目名称--->企业等级


rule "sg_pddj_27_4"  
salience 900  
no-loop true  
activation-group "sg_pddj"
when  
    $inpojo : SgBbPddjPojo((gclx == 27) && (jzwcs<=14) && (dwkd<=24))  
then          
    System.out.println("工程类型为:27 房屋建筑工程  return :CENGSHU,KUADU,GUIMO   zzdj=4  三级");  
    retPojo.setZzid(10);//资质UID
    retPojo.setZzidstr("10");//资质等级UID str 可能有多个
    retPojo.setZzdj(11);//资质等级 三级 
    retPojo.setZdpbrs("xmfzr:1,xmjsfzr:1,sgy:1,aqy:1,zjy:1,zly:0,xxgly:0");//最低配备人数String
    retPojo.setQyzzpdbz("CENGSHU,KUADU,GUIMO");
    retPojo.setEnabled(true);
end

rule "sg_pddj_27_3"  
salience 900  
no-loop true  
activation-group "sg_pddj"
when  
    $inpojo : SgBbPddjPojo((gclx == 27) && (jzwcs<=28) && (dwkd<=36))  
then          
    System.out.println("工程类型为:27 房屋建筑工程  return :CENGSHU,KUADU,GUIMO   zzdj=3  二级");  
    retPojo.setZzid(10);//资质UID
    retPojo.setZzidstr("10");//资质等级UID str 可能有多个
    retPojo.setZzdj(12);//资质等级 二级 
    retPojo.setZdpbrs("xmfzr:1,xmjsfzr:1,sgy:1,aqy:1,zjy:1,zly:0,xxgly:0");//最低配备人数String
    retPojo.setQyzzpdbz("CENGSHU,KUADU,GUIMO");
    retPojo.setEnabled(true);
end 

rule "sg_pddj_27_2"  
salience 900  
no-loop true  
activation-group "sg_pddj"
when  
    $inpojo : SgBbPddjPojo((gclx == 27) && (jzwcs<=40))  
then          
    System.out.println("工程类型为:27 房屋建筑工程  return :CENGSHU,KUADU,GUIMO   zzdj=2  一级");  
    retPojo.setZzid(10);//资质UID
    retPojo.setZzidstr("10");//资质等级UID str 可能有多个
    retPojo.setZzdj(13);//资质等级 一级 
    retPojo.setZdpbrs("xmfzr:1,xmjsfzr:1,sgy:1,aqy:1,zjy:1,zly:0,xxgly:0");//最低配备人数String
    retPojo.setQyzzpdbz("CENGSHU,KUADU,GUIMO");
    retPojo.setEnabled(true);
end 

rule "sg_pddj_27_1"  
salience 900  
no-loop true  
activation-group "sg_pddj"
when  
    $inpojo : SgBbPddjPojo(gclx == 27)  
then          
    System.out.println("工程类型为:27 房屋建筑工程  return :CENGSHU,KUADU,GUIMO   zzdj=4  特级");  
    retPojo.setZzdj(10);//资质等级 特级 
    retPojo.setEnabled(true);
end 